export default {
  serverError: {
    message: "An internal server error occurred, please try again.",
    code: "00001",
  },
  verificationCodeTitle: "Verification Code",
  verificationCodeBody: "Here is your confirm code:",
  welcomeCode: "Welcome to the App",
  "00005": "Please provide all information to send a code.",
  "00006": "Access denied. No token provided.",
  "00007": "Invalid user id.",
  "00009":
    "Could not find verified user with the given token and id. Be sure that the account was verified and activated.",
  "00011": "Your session is expired, please log in again.",
  "00012": "Invalid token. the token may have expired.",
  "00017": "Access denied. You do not have permission to access.",
  "00023": "Provided id is not a valid object id.",
  "00024": "Too many request.",
  "00025": "Please provide all the required fields!",
  "00026": "Please provide a valid email!",
  "00027":
    "Please provide a password that is longer than 6 letters and shorter than 20 letters.",
  "00032": "An account with this email address already exists.",
  "00035": "New user registered successfully.",
  "00036": "An account with this email address was not found.",
  "00043": "Your email is not activated, please register firstly.",
  "00044": "Your email is not verified, please verify your email.",
  "00045": "You have entered an invalid email or password.",
  "00047": "You logged in successfully.",
  "00048": "The code is sent to your email successfully.",
  "00050": "Successfully logged out.",
  "00052": "The user could not find.",
  "00053": "Please send a verification code.",
  "00054":
    "The code you enter does not match with the code we sent to your email. Please check again.",
  "00055": "Invalid token. the token may have expired.",
  "00058": "Your email address was verified successfully.",
  "00059": "Please provide refresh token.",
  "00061": "The provided token does not match with the user, please login.",
  "00062": "The token has expired, please login.",
  "00063": "The token could not be verified, please login.",
  "00065": "The token is refreshed successfully.",
  "00066": "Please provide a password longer than 6, less than 20 characters.",
  "00068": "The new password was created successfully.",
  "00072":
    "Your old password does not match with the password you entered, please enter the correct password.",
  "00073":
    "Your new password should not be same with the old one, please try a different password.",
  "00076": "Your password was changed successfully.",
  "00077":
    "Please provide a name that is longer than 3 letters and shorter than 30 letters.",
  "00084": "There is already a user with this username, please enter another.",
  "00086": "Your profile information was changed successfully.",
  "00089": "The user information has gotten successfully.",
  "00092": "Your account was deleted successfully.",
};
